# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Master push

on:
  push:
    branches: [master]

jobs:
  build:
    uses: ./.github/workflows/build.yml
  release:
    needs: build
    uses: ./.github/workflows/release.yml
