# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull request

on:
  pull_request:
    branches: [master]

jobs:
  validate:
    uses: ./.github/workflows/validate.yml
  # TODO: Remove before merging
  build:
    needs: validate
    uses: ./.github/workflows/build.yml
